/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {

    @Test
    public void testNoErrorsFile() {

        String actual = App.readJS("src/test/resources/no-error.js");
        assertTrue(!actual.contains("Line "+"3: Missing semicolon."+"\n"));

    }


    @Test
    public void testOneErrorFile() {
        String actual = App.readJS("src/test/resources/one-error.js");
        assertTrue(!actual.contains("Line "+"3: Missing semicolon."+"\n"));
    }

    @Test
    public void testFewErrorsFile() {
        String actual = App.readJS("src/test/resources/few-error.js");
        assertTrue(!actual.contains("Missing semicolon."));
    }

    @Test
    public void testManyErrorsFile() {
        String actual = App.readJS("src/test/resources/many-errors.js");
        assertTrue(!actual.contains("Missing semicolon."));
    }

    @Test
    public void testEmptyFile() {
        String actual = App.readJS("src/test/resources/empty-file.js");
        assertEquals("",actual);
    }


}
