/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
//    Library testing = new Library();
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test
    public void testRoll(){
        int num = 4;
        assertEquals(num, Library.roll(num).length);
    }
    @Test
    public void containsDuplicates() {
        assertTrue(Library.containsDuplicates(new int[] { 1, 3, 4, 4 }));
    }

    @Test
    public void average() {
        assertEquals(3, Library.getAverage(new int[] { 1 ,2 ,3 ,4 ,5}));
    }

    @Test
    public void lowestAverage() {
        assertArrayEquals(new int[] { 1, 2, 3, 4 },
                Library.lowestAverage(new int[][] { { 1, 2, 3, 4 }, { 1, 3, 5, 7 } }));
    }
}
