/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("------- First func --------------");
        roll(4);
        System.out.println("------- Second func --------------");
        int num[] = {1, 2, 5, 7,2};
        System.out.println("Is the  the array contains duplicate values? The answer is:" + containsDuplicates(num));
        System.out.println("------- Third func --------------");
        int arr[] = {1, 2, 4, 3, 5};
        System.out.println("the average of all the values in the array is:" + getAverage(arr));
        System.out.println("------- Fourth func --------------");
        int[][] fourArr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        System.out.println("The Lowest average array ");
        System.out.println(Arrays.toString(lowestAverage(fourArr)));
    }

    public static int[] roll(int n) {
        int arr[] = new int[n];

        for (int i = 0; i < n; i++) {
            arr[i] = (int) (Math.random() * ((6 - 1) + 1)) + 1;
        }
        System.out.println(Arrays.toString(arr));
        return arr;

    }

    public static boolean containsDuplicates(int[] num) {
        for (int i = 0; i < num.length; i++) {
            for (int j = 0; j < num.length; j++) {
                if (i != j) {
                    if (num[i] == num[j]) {
                        return true;
                    }
                }
            }
        }
            return false;
        }

        public static double getAverage(int[] array){
            double sum = 0;
            for (int j : array) {
                sum += j;
            }
            return sum / array.length;

        }
        public static int[] lowestAverage( int[][] arr){
            double sum = 0;
            double avg = 0;
            double lowestAvg = 0;
            int index = 0;

            for (int i = 0; i < arr.length; i++) {
                for (int j = 0; j < arr[i].length; j++) {
                    sum += arr[i][j];
                    avg = sum / arr[i].length;
                    if (i == 0) {
                        lowestAvg = avg;
                    }
                }
                if (avg < lowestAvg) {
                    lowestAvg = avg;
                    index = i;
                }
                sum = 0;
                avg = 0;
            }
            return arr[index];
        }
    }

