/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant res = new Restaurant("turbo",5,10);
        System.out.println(res);
        Review review = new Review("bad","march",5);
        Review rev2 = new Review("Nice", "Marah", 4);
        res.addReview(review);
        res.addReview(rev2);
        System.out.println(rev2.toString());
        System.out.println(res.toString());
    }
}
